name: CI

on:
  push:
    branches: [develop, master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Use Node.js 12.22.4
        uses: actions/setup-node@v1
        with:
          node_version: '12.22.4'

      - name: yarn install
        run: yarn install --frozen-lockfile --link-duplicates --silent;
      - name: yarn lint
        run: yarn lint
      - name: yarn test
        run: yarn test:related
